name: C CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install buildtools
        run: |
          sudo apt install devscripts debhelper
      - name: Build .deb package
        run: |
          make deb
